### ISSUE TITLE
[3.0-beta8] Unsupported action in pump. Use AndroidAPS UI only!

### ISSUE THREAD

**Issue by vmichalec** [nightscout/AndroidAPS#1028]
3.0-beta8, Dana R (03/03/B3)

Today my action was changing the profile from current 95% -> 110% for 10 min. After this I have got following:

```
15:01:21.723 [RxCachedThreadScheduler-6] D/NOTIFICATION: [NotificationStore.add():60]: Notification received: Unsupported action in pump. Use AndroidAPS UI only!
```
I did same profile change also right now but currently without problems.

I don't use any other app for pump, I don't have the app from dana installed on my phone. I don't enter anything manually to the pump.
I did receive same message at night few days before but I didn't manage to get the logs before they were deleted. So I have only one case in logs.

[Logs.zip](https://github.com/nightscout/AndroidAPS/files/7651559/Logs.zip)

**Comment by MilosKozak** [comment]
it was caused by previous error in communication so AAPS didn't know about pump state.
AAPS behaviour was correct in this case and sanity check recovered from this sutuation well (even with message to user)
I'd recommend upgrade pump firmware to v2 anyway to increase safety and better handle such errors
