### ISSUE TITLE
[3.0-beta11] Dana RS Pairing requested

### ISSUE THREAD

**Issue by vmichalec** [nightscout/AndroidAPS#1138]
Not sure what was the trigger but AAPS started to request pairing keys for the dana-rs pump. I entered them and it continues to work. Previous pairing keys for AAPS 3.0 were imported from configuration file if I remember correctly.

Here are logs if there can be found something useful: [AndroidAPS.zip](https://github.com/nightscout/AndroidAPS/files/7830462/AndroidAPS.zip)

Either way I suggest here to sent information about this state (pump disconnected - pairing requested) to nightscout. Same as we have messages like aaps was restarted, time to eat and so on. It will be useful for parents to be informed about this non-working aaps state on NSClient side.

**Comment by MilosKozak** [comment]
Unstable communication or bugs in phone BT stack can cause reset of pairing info in AAPS. This is related to RS protocol and cannot be changed. When this happen you usually already see in NS pump status outdated (red). It has to be checked and resolved on child's phone anyway. I don't think more notifications is needed.
If it happens regulary I'd recommend change phone anyway because there is no "good" solution for this issue
