### ISSUE TITLE
Autosense reset after changing faulty catheter / POD

### ISSUE THREAD

**Issue by filipwoz** [nightscout/AndroidAPS#1206]
By using Omnipod it happens from time to time that on the last day the catheter is not delivering 100% of the ordered insulin (see also the expecience reported in https://de.loopercommunity.org/t/pro-und-contra-aaps-mit-omnipod-dash/8789) which causes the Autosense to go up in that time. After changing the Pod I expect that everything works again correctly - i.e. Autosense should be reset to initial state.
Currently it does not happen (tested with v3 RC1) and I needed to reset the Autosense using a workaround (changed the Autosense algorithm to another one and back to original one) to achieve it.
I thnik this would be usefull not only for Omnipod but generally by any fault catheter switch.

**Comment by nicoleloop** [comment]
Oh my, could that be the reason why I run so low for the 12 hours following a Dash Pod change? I did not even think to check autosense, thank you for mentioning this issue, I'll use your work-around immediately as I just switched Pods myself.

**Comment by avereha** [comment]
Please add more details:
 - what Autosens algorithm are you using?
 - screenshot with the "Autosens data"
 - screenshot with the Autosens output that does not reset after pod change.

**Comment by avereha** [comment]
Any screenshot that shows when Autosense is not reset after pod change.

**Comment by Freloner** [comment]
Hey there, just changed a pod and Autosens is reset !

[Logs link, around 08:33](https://linksharing.samsungcloud.com/iO2bennZulGl)

![Screenshot_20220128-083945_AndroidAPS.jpg](https://user-images.githubusercontent.com/87416963/151507534-9ba6db3c-060d-436f-9dfe-1385594867b0.jpg)

![Screenshot_20220128-084641_AndroidAPS.jpg](https://user-images.githubusercontent.com/87416963/151507548-97e35c89-4db6-40fd-a2d8-e910f298edaa.jpg)

**Comment by MilosKozak** [comment]
@filipwoz are you able to replicate?

**Comment by nicoleloop** [comment]
Yes I was able to get proof of autosens Not Resetting after a pod change.



Sent from my T-Mobile 5G Device



-------- Original message --------
From: Milos Kozak ***@***.***>
Date: 1/29/22 1:19 AM (GMT-08:00)
To: nightscout/AndroidAPS ***@***.***>
Cc: nicoleloop ***@***.***>, Comment ***@***.***>
Subject: Re: [nightscout/AndroidAPS] Autosense reset after changing faulty catheter / POD (Issue #1206)


@filipwoz<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffilipwoz&data=04%7C01%7C%7C4b77d13b69294f00601908d9e3086a43%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637790447552706646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=weyYKtxkFfzehUeRUkOjMuxMMBwsxq5CQyq5Z6XHDHU%3D&reserved=0> are you able to replicate?

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnightscout%2FAndroidAPS%2Fissues%2F1206%23issuecomment-1024873948&data=04%7C01%7C%7C4b77d13b69294f00601908d9e3086a43%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637790447552706646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yfj%2BmEhPon2Ff5Wtk5fRzW%2BdHEmfzDYudvoQs8PlbRk%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIU7LKWF533C5HA4GPERGGLUYOWJBANCNFSM5MMMZRZQ&data=04%7C01%7C%7C4b77d13b69294f00601908d9e3086a43%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637790447552706646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BObum6mJOTcSfjTtWkTyCgJWKeblq4%2FaUfJ2rVNm6%2Bk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C4b77d13b69294f00601908d9e3086a43%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637790447552706646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pZUJjTmIISyUBIB7cr4XMbmoIHLZOmHtxX1MZ66Ou1o%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C4b77d13b69294f00601908d9e3086a43%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637790447552706646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0bcyRTw3tm3DfSe%2Fz2FYz0rA8OjU9MG28RCxFhsYny4%3D&reserved=0>.

**Comment by nicoleloop** [comment]
Sent from my T-Mobile 5G Device



-------- Original message --------
From: nicoleloop ***@***.***>
Date: 1/29/22 3:18 AM (GMT-08:00)
To: nightscout/AndroidAPS ***@***.***>
Cc: nicoleloop ***@***.***>, Your activity ***@***.***>
Subject: Re: [nightscout/AndroidAPS] Autosense reset after changing faulty catheter / POD (Issue #1206)


Yes I was able to get proof of autosens Not Resetting after a pod change.



Sent from my T-Mobile 5G Device



-------- Original message --------
From: Milos Kozak ***@***.***>
Date: 1/29/22 1:19 AM (GMT-08:00)
To: nightscout/AndroidAPS ***@***.***>
Cc: nicoleloop ***@***.***>, Comment ***@***.***>
Subject: Re: [nightscout/AndroidAPS] Autosense reset after changing faulty catheter / POD (Issue #1206)


@filipwoz<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffilipwoz&data=04%7C01%7C%7C4b77d13b69294f00601908d9e3086a43%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637790447552706646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=weyYKtxkFfzehUeRUkOjMuxMMBwsxq5CQyq5Z6XHDHU%3D&reserved=0> are you able to replicate?

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnightscout%2FAndroidAPS%2Fissues%2F1206%23issuecomment-1024873948&data=04%7C01%7C%7C4b77d13b69294f00601908d9e3086a43%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637790447552706646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yfj%2BmEhPon2Ff5Wtk5fRzW%2BdHEmfzDYudvoQs8PlbRk%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIU7LKWF533C5HA4GPERGGLUYOWJBANCNFSM5MMMZRZQ&data=04%7C01%7C%7C4b77d13b69294f00601908d9e3086a43%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637790447552706646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BObum6mJOTcSfjTtWkTyCgJWKeblq4%2FaUfJ2rVNm6%2Bk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C4b77d13b69294f00601908d9e3086a43%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637790447552706646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pZUJjTmIISyUBIB7cr4XMbmoIHLZOmHtxX1MZ66Ou1o%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C4b77d13b69294f00601908d9e3086a43%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637790447552706646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0bcyRTw3tm3DfSe%2Fz2FYz0rA8OjU9MG28RCxFhsYny4%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnightscout%2FAndroidAPS%2Fissues%2F1206%23issuecomment-1024891916&data=04%7C01%7C%7Ca4f46379cc044b003ec108d9e3192148%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637790519332512955%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0URkRdY19JLnwxK9SXLrE2LmD%2BThcTFOorqCK%2BRbpV8%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIU7LKQ25L5QQZXNJ4OE4OLUYPEJXANCNFSM5MMMZRZQ&data=04%7C01%7C%7Ca4f46379cc044b003ec108d9e3192148%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637790519332512955%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SPqTFifVHrqrFFzS%2FXwBspqH8zdGCjhJkyL%2Bfrp21cw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ca4f46379cc044b003ec108d9e3192148%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637790519332512955%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JnEUj6Y0tsmlpjR7DNEyTUakBxwunWi%2FqbIfWADe8%2Bo%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ca4f46379cc044b003ec108d9e3192148%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637790519332512955%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xk56%2F1Cv6CS%2BAsd0OQwWceafGeeVWie9ssqWjim6kGw%3D&reserved=0>.

**Comment by filipwoz** [comment]
@MilosKozak I will let you know once I change the pod once again. By the last 2 ones I had some other problems and I was not able to observe it properly.
I have however one more idea what might be "wrong" here. I observed that also by profile change Autosense is not being reset immediately - it always takes some minute or two until I can see again 100% by the Autosense Icon. So maybe it is not that it is **not reset** but the reset is only **delayed**?
I will observe it next time and come back to you.

**Comment by MilosKozak** [comment]
you can observe it first after next BG

**Comment by filipwoz** [comment]
OK, yesterday I observed  the Autosense after the POD change and it got reset after the next BG. So looks like by my original observation I had too less patience.
