### ISSUE TITLE
[AAPS 3.0.0.1] Master password & biometric popup at the same time, on app start

### ISSUE THREAD

**Issue by JazzZ1** [nightscout/AndroidAPS#1356]
Time of occurance in log: 20.02.2022, 21:37

Description: I have set all security settings to biometric:
![Screenshot_20220220-181614_AndroidAPS](https://user-images.githubusercontent.com/64336417/154863154-a4552408-ed8c-4c4f-915c-284761c61edc.jpg)
Still sometimes on app start there are two popups (In front: Biometric; in the back: master password) showing at the same time (I can't make a Screenshot of that, because of Android security reasons). So i first have to do biometrics validation, then I have to put in the master password.

Build: 479bfc410-2022.02.06-18:41

**Comment by JazzZ1** [comment]
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/8104900/AndroidAPS.log)

**Comment by Andries-Smit** [comment]
App protection is called on resume, and did not care if it was already asking for authentication.... When the bio authentication is already active, Android cancels it. Therefor falling back to app master password.
It reproduce the issue, change orientation of the app. Or open and close app multiple times without authenticating.

This issue will be fixed in PR #1409 commit cfa64162b0b5c4d6a60916bec55087b2df758a0c
