### ISSUE TITLE
MINOR / WIDGET / Color difference for mid-high BGs

### ISSUE THREAD

**Issue by robertrub** [nightscout/AndroidAPS#1604]
AAPS doesn't use the same color on the app and widget for mid-high BGs

App

![Screenshot_20220411-100433_AndroidAPS.jpg](https://user-images.githubusercontent.com/76626474/162697406-a8a5e73b-1ca3-4042-9b64-339af5b1d61b.jpg)

Widget

![Screenshot_20220411-100412_One UI Home.jpg](https://user-images.githubusercontent.com/76626474/162697499-66e04554-793e-401c-b43d-9ddfbf70047f.jpg)

**Comment by osodebailar** [comment]
The color from the widget is taken from the default color.xml. 
This are the colors for the light mode in aaps.
In the light mode yellow is not possible , because yellow on white background is hard to see. 
Aaps itself is in darkmode and has another color.xml table.
The widget itself has no possibilities for dark or light mode. It's not implemented by google until now.

**Comment by MilosKozak** [comment]
could we create special color names for widget which would match dark mode?

**Comment by osodebailar** [comment]
@MilosKozak : yes, I will have a look. I will prepare a PR this evening

**Comment by osodebailar** [comment]
PR is ready: https://github.com/nightscout/AndroidAPS/pull/1605
