### ISSUE TITLE
3.0.0.2-dev-l: mmol/l / mg/dl bug

### ISSUE THREAD

**Issue by diabetesdiyaps** [nightscout/AndroidAPS#1805]
Build version: 3.0.0.2-dev-l

Yesterday setup a test environment for dynISF using my phone and personal accounts (Nightscout, Heroku, xDrip) for it. All have the same version as my girlfriend. My T1D girlfriend is using the production environment ;-) 

Found a bug in dev-l in conversion mmol/l and mg/dl: 

- We use mmol/L settings, but when using bolus calculator, 'blood glucose' value shows in Nightscout (most recent v14.2.5) report Treatments as mg/dl instead of mmol/l. After reverting back to 3.0.0.2 and using bolus calculator the same I see 'blood glucose' value is stored again as mmol/l.

- Also, after using AndroidAPS bolus calculator entering value in mmol/l the overview screen suddenly shows the value as mg/dl. When changing AndroidAPS unit setting from mmol/l to mg/ml overview screen seems to show to correct value.

See screenshots for a deep dive: 

![treatments](https://user-images.githubusercontent.com/77556597/171996743-f76d88e4-e8a5-4280-874a-83ab0f72ca26.png)
With dev-l in main window when I switch units it goes wrong:

![overview mmoll](https://user-images.githubusercontent.com/77556597/171996742-5a9dfe93-8a79-453c-93d3-1525f8ef4768.png)
Set AndroidAPS units in mmol/l

![overview mgdl](https://user-images.githubusercontent.com/77556597/171996741-c072f7d2-7eb7-4ef7-9350-b1f865cc00ea.png)
Set AndroidAPS units in mg/dl

![nostubs](https://user-images.githubusercontent.com/77556597/171996744-3433e26e-43f2-4923-b125-e02c698ea540.png)
No stubs in this test-round ;) 

For my the upcoming days / weeks it's possible to re-test, upload log files or build a new dev version to test. Love to help. 

Dev's, great job so far !!

All the best,
Peter

**Comment by petervanrijt** [comment]
Created this issue this afternoon with my testing account. Response using my personal account. Did some testing tonight:

### AndroidAPS 3.0.0.2

1. AndroidAPS in mmol/l, Nightscout in mmol/l. Bolus wizard BG 5.5, carbs 20g. In Nightscout report treatments: BG 5.5
2. AndroidAPS in mmol/l, Nightscout in mg/dl . Bolus wizard BG 5.5, carbs 20g. In Nightscout report treatments: BG 5.5
3. AndroidAPS in mg/dl , Nightscout in mmol/l. Bolus wizard BG  99, carbs 20g. In Nightscout report treatments: BG 99
4. AndroidAPS in mg/dl , Nightscout in mg/dl . Bolus wizard BG  99, carbs 20g. In Nightscout report treatments: BG 99

### AndroidAPS 3.0.0.2-dev-l

5. AndroidAPS in mmol/l, Nightscout in mmol/l. Bolus wizard BG 5.5, carbs 40g. In Nightscout report treatments: BG 99
6. AndroidAPS in mmol/l, Nightscout in mg/dl . Bolus wizard BG 5.5, carbs 40g. In Nightscout report treatments: BG 99
7. AndroidAPS in mg/dl , Nightscout in mmol/l. Bolus wizard BG  99, carbs 40g. In Nightscout report treatments: BG 99
8. AndroidAPS in mg/dl , Nightscout in mg/dl . Bolus wizard BG  99, carbs 40g. In Nightscout report treatments: BG 99

Expected in 5 and 6 was a BG in Nightscout report treatments of 5.5 instead of 99.

**Comment by petervanrijt** [comment]
Hi, 

An update on the findings. Writing to NIghtscout still is in mg/dl instead of mmol/l. But, in a chat with another Dutch user I heard he did not have trouble with his screen "mmol/l / mg/dl stripes" to occur. So I have tested again. 

I saw when the switch is "too fast" there's a screen error (see below). When I don't wait for the blue bar to completely finished to right the screen has "mmol/l mg/dl stripes". A good workaround is to Exit the app and restart, the screen will be OK after loading. 

Perhaps an idea to pop-up a message after switching from mg/dl to mmol/l to wait completely for the screen to load, or to Exit the app and reboot immediately?

Thanks and all the best,
Peter

![171996742-5a9dfe93-8a79-453c-93d3-1525f8ef4768](https://user-images.githubusercontent.com/13611404/172168374-fd670b99-0cc6-4cca-a33b-2e7ae7c7598d.png)

**Comment by MilosKozak** [comment]
issue is on NS side. it doesn't convert value to units selectwed in settings.
I set at least upload to units selected in AAPS https://github.com/nightscout/AndroidAPS/commit/70f365960052ec28f6844538559c8cd38bf32220
So far it was always in MGDL

**Comment by petervanrijt** [comment]
Thank you @MilosKozak !
