### ISSUE TITLE
Considering lowest possible basal value willst profile reduction

### ISSUE THREAD

**Issue by GerritosSteen** [nightscout/AndroidAPS#1816]
Currently, I cannot set the profile to a lower rate than 100% because at least one basal value is set to the lowest possible value already. This way, I am unable to define a lower profile for my son for doing sports (higher IC, lower ISF, lower basal).
 
I.e. when I have set one basal value of 0.05 units using an Omnipod DASH, this unit cannot be reduced anymore as the minimum of the Omnipod DASH is 0.05 units.
 
I suggest to enhance the logic of profile reduction by considering the lowest possible minimum that the pump is able to handle. Referring to above mentioned example, the profile reduction of 80% would consider one or more values that already are on their minimum and would not try to reduce them by 20% but would let them with the already defined minimum.
 
Example:
 
Basal values
100%; profile 80% current logic; profile 80% new logic
0.05;ERROR;0.05
0.07;0.05;0.05
0.09;0.05;0.05
0.10;0.10;0.10
0.15;0.12;0.12

**Comment by Philoul** [comment]
Interesting suggestion. @MilosKozak do you think we could manage profiles without pump constraints (for ex with rates or TBR << lower limit available by the pump) and let the loop manage with an alternance of 100% and zero temp to fit requested values...
Profiles built by autotune are with 3 digits (and rounding to pump capabilities is perfectly done by the driver...).

**Comment by MilosKozak** [comment]
it's doable (i think easy). The question is if it's good idea. when you set 30% of small profile, you expect 30% of insulin. but it could easy happen you stay at 100% in some ranges

**Comment by Philoul** [comment]
I didn't correctly understood the suggestion, I think we should remove in local profile (and tbr) the constraint of pump minimum values and allow basal rates or tbr of 0.02 or 0.01U/h even if pump limitation is 0.05U/h mini.
The basal rate set into the pump will be 0.05 (mini value) but it shouldn't rise an error (because it's pump minimum value), then iob calculation will be done with profile values so the loop will automatically adjust with zero temp to have an average delivered insulin equals to profile or tbr rate...

**Comment by mordechi-david** [comment]
I too have encountered this problem in some children

**Comment by Philoul** [comment]
Yes, but in this case the safety issue is due to the pump, not to aaps...
Currently no other choice for parents to change the pump to another one with lowest constraints (if available), or use diluted insulin with a correct convertion of the profile...
But none of these solution is really satisfactory for young kids.
Do you have other ideas in mind?

**Comment by Philoul** [comment]
Maybe in this case we could just add a warning to inform the user that basal rate set in pump is greater than profile / tbr request due to pump constraints...

**Comment by mordechi-david** [comment]
> זה ישבור את ההנחה הבסיסית שהפרופיל המשוער הוא פרופיל שנטען במשאבה

I totally agree with this because in any communication problem etc. it is very important that the active profile remains, which will not happen in these cases

**Comment by MilosKozak** [comment]
i don't like the idea making the code complicated for edge cases like this. complicated code means more possible bugs
there are still 2 possible solutions
* prepare extra profile (noit just %) and switch to it
* use diluted insulin

**Comment by GerritosSteen** [comment]
Thanks for the exchange. I understand the inconsistencies that would raise by this request. I'll close the issue accordingly
