### ISSUE TITLE
[2.8.0] Add prime/fill and pump battery change to virtual pump insulet omnipod

### ISSUE THREAD

**Issue by happygirlnyc70** [nightscout/AndroidAPS#187]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://androidaps.readthedocs.io/en/latest/EN/Usage/Accessing-logfiles.html
- Open an issue at https://github.com/nightscout/AndroidAPS/issues/new

**Comment by andyrozman** [comment]
If pump has option to change battery, then virtual pump has this option. On omnipod you can't change the battery, so Virtual Pump doesn't support it either.
While Omnipod has Prime/Fill, that prime/fill is very specific to Omnipod, and its not done through AAPS default methods, which is why this is not enabled.
