### ISSUE TITLE
[Improvement] Allow a smaller minimum value for "Pump unreachable threshold"

### ISSUE THREAD

**Issue by ArthurusDent** [nightscout/AndroidAPS#237]
Right now my setup with a Medtronic pump struggles with connection problems and I'm getting a pump unreachable alarm about two or three times a day. Quite often this happens at night. 

This is not a bug report though, as I'm still investigating the source of the problem.

What would help me is this: The default and at the same time minimum value for "Pump unreachable threshold" is 30 min. In my opinion that's too long, especially at night. It would be great, if the minimum allowed value could be set to maybe 5 min.

**Comment by AdrianLxM** [comment]
AndroidAPS wakes up for maintenance every 5 minutes - but it does not connect to the pump every 5 minutes.

It only does so if it needs to in order to change something or latest it tries after 15 minutes of no connection, AndroidAPS will try to connect.
It might happen that the 15 minute wakeup doesn't connect as it in fact was only 14:55 minutes since the last connection.
Then the forced connection would happen at the 20 minute mark.

So the minimum time to avoid constant false positive alarms would be 25 minutes.
If you then cannot connect because you happen to run away from the phone for just a few seconds this would also mean a false-positive alarm.

30 minutes therefore seems quite reasonable as minimum time without connection to alarm for.
