### ISSUE TITLE
[DEV] Status Line is not showing all information 

### ISSUE THREAD

**Issue by triplem** [nightscout/AndroidAPS#2448]
The Statusline shows the Date of the last reservoir change as well the the age of the Battery, but not it's values. 
On the Action Screen only parts of the value are shown. In Landscape Mode this seems to be working fine.

I would prefer of the value is shown before the age, ao to be able to show the value instead of the age of both.

**Comment by triplem** [comment]
The Phone is a OnePlus 8T.

**Comment by MilosKozak** [comment]
screenshot?

**Comment by triplem** [comment]
![Screenshot_2023-03-04-10-15-28-23_3eaa31bb2c2a38a1c605d9dc918cf694.jpg](https://user-images.githubusercontent.com/160079/222890058-bbad342f-c8b7-4b22-9207-7a010bcff011.jpg)

![Screenshot_2023-03-04-10-15-16-06_3eaa31bb2c2a38a1c605d9dc918cf694.jpg](https://user-images.githubusercontent.com/160079/222890071-0c3cdd41-10cf-4856-b3d1-4b4d447fa0c9.jpg)

![Screenshot_2023-03-04-10-15-11-23_3eaa31bb2c2a38a1c605d9dc918cf694.jpg](https://user-images.githubusercontent.com/160079/222890080-c2f99fe7-8087-4f5e-a6c4-7040863371d4.jpg)

![Screenshot_2023-03-04-10-17-30-80_3eaa31bb2c2a38a1c605d9dc918cf694.jpg](https://user-images.githubusercontent.com/160079/222890111-0e1782ae-e926-403e-ad6a-5c3e31260695.jpg)

**Comment by MilosKozak** [comment]
this doesn't have good solution. formating is done by android

**Comment by vanelsberg** [comment]
Screen look good for me.
Think is is phone or phone settings specific, maybe check phones display setting like resolution en/or font size?

**Comment by swissalpine** [comment]
If you select "Skin: Low resolution skin" in the settings, then the superfluous, space-eating labels like "Alter:" and "Abgegeben:" are hidden.
In the past (some years ago), these labels did not exist either. And since the information is actually self-explanatory, we could basically say goodbye to it again. Or @MilosKozak?

**Comment by vanelsberg** [comment]
> If you select "Skin: Low resolution skin" in the settings, then the superfluous, space-eating labels like "Alter:" and "Abgegeben:" are hidden. In the past (some years ago), these labels did not exist either. And since the information is actually self-explanatory....

Translations may give problems, like in this case.
I think for most this is not a problem. How about just showing icons, lik eon main overview, pump/reservoir/sensor?

**Comment by triplem** [comment]
Well, setting "Low Resolution" dies Work. But eg "Abgegeben" is then still shown.

#
![Screenshot_2023-03-09-18-33-12-85_3eaa31bb2c2a38a1c605d9dc918cf694](https://user-images.githubusercontent.com/160079/224109121-73504778-6602-448c-81d3-7ade674d8a7e.jpg)
 
Also this does not really has an effect on the overview 

![Screenshot_2023-03-09-18-35-21-22_3eaa31bb2c2a38a1c605d9dc918cf694](https://user-images.githubusercontent.com/160079/224109363-a1db2da9-1a5e-4501-8232-5a7ca0316598.jpg)

Still I think that the level in the reservoir is more important then the age. Could this be swapped? Same is probably true for the battery level (well, at least partly).

**Comment by Philoul** [comment]
> Still I think that the level in the reservoir is more important then the age. Could this be swapped? Same is probably true for the battery level (well, at least partly).

On low res screen, there are less information than on higher res:

With my phone for ex, I have age and level for reservoir, age and level for battery

![Screenshot_20230326-172552_AAPS.jpg](https://user-images.githubusercontent.com/52934600/227786204-90827c22-5d65-4313-a781-8e01be3d01ac.jpg)

But it's a good idea to keep levels and hide ages on low res...

**Comment by aliswalker** [comment]
@Philoul without going OT as this does affect status lights on low res – Do you know why your COB doesn't display a timestamp like mine/OP? It's on a new line which for low res users means scrolling with status lights on.

![LowRes](https://user-images.githubusercontent.com/70867813/233593488-721162ce-90df-4a8e-924d-889ae4dea05c.png)

Yours both also show TBR % vs U/h which was proposed as a setting under #2200

**Comment by Philoul** [comment]
1) The time below COB value is only visible in dev branchs, not in master (I just hide it on my own version).

2) The format of TBR is directly linked to the pump driver and how the pump manage this information:
- for ex with Insight pump, the driver send a % to the pump for standard tbr, and managed the extended tbr by a square bolus. That's why I see in Overview a % when it's a standard tbr is running, and an absolute rate value when an extended tbr is running.

So if your pump driver send to your pump an absolute rate when a tbr is set, then you will see the absolute rate in overview... (I think it's to be able to check directly with your pump UI if both informations are consistant)
