### ISSUE TITLE
Dash resovouir empty, No Automated actions 

### ISSUE THREAD

**Issue by DrunoL** [nightscout/AndroidAPS#3351]
When the resovoir of the Pod is empty, but the pod ist not expired, no Action ist taken automatcally, so the bloodsugar rises without information. 

To say: The best App ever coded, thank you!

![Screenshot_20240527-155807~2](https://github.com/nightscout/AndroidAPS/assets/50956503/5c2b0736-b898-4fdc-aecc-b033a9a88322)

![Screenshot_20240527-155734~2](https://github.com/nightscout/AndroidAPS/assets/50956503/f62933f3-c159-4d30-82e2-df1f0b6bcf34)

**Comment by Philoul** [comment]
For me it looks more as a pump issue that should be raised in Pump manufacturer...
On my Insight pump (Accu-Chek), alerts comes from pump, not from pump driver, and pump driver only provide the UI to cancel alert...

This is for me a safety issue but on pump side 🤔

I agree we could probably improve pump driver on this topic to provide an alert from phone, but this will not have the same strength than DASH screamer, and can be disabled within phone settings (I don't know if DASH PDM provides this kind of alert or not...).

**Comment by vanelsberg** [comment]
Did you bolus the 10.00U 16:00h before or after the DASH tab was reporting 0.0 insuline left?
And (according to your IOB) this bolus executed successfully?

Note that the fact reservoir is reporting 0.00E left (Pod starts beeping) does not mean that there is the DASH Pod is completely empty. There may still be some units left in the pump. Once a bolus command or set TBR fails due to the Pod being out of insulin, I expect the DASH pump to report a failure or scream?

**Comment by Philoul** [comment]
In screenshot I see that latest bolus was delivered 2h22min earlier and was probably a SMB (0.15U).
But we don't see if 10U bolus started, or not (only the dot in main graph).

**Comment by emmatovar27** [comment]
In the dash preferences you can set up an alarm for low reservoir.  

The minimum is 5 this can help as a reminder to change the pod! :) 

![Screenshot_20240901-215939](https://github.com/user-attachments/assets/37e61383-5034-4025-b529-554344950788)
