### ISSUE TITLE
[Improvement] Improve UX for Config Builder by only showing selected options

### ISSUE THREAD

**Issue by olorinmaia** [nightscout/AndroidAPS#3563]
The Config builder is starting to get very long with the growing pump/cgm support. Should we considering adding some sort of minimizing feature? That way all non-selected options can be automatically hidden, and only show the ones that you have selected, and add a button so you can expand the list to show all options. 

Thoughts or possibly other ideas how to improve Config Builder?
Illustration of how it could be done:
![image](https://github.com/user-attachments/assets/e77e5aa1-76ca-487d-ab90-97ae01e5522c)

How the long the list is actually today :)

![image](https://github.com/user-attachments/assets/81e1ea28-5812-4a19-9b4c-2b5d07a9819d)

**Comment by olorinmaia** [comment]
I like it :) 

Do you have a branch for this to be tested ? or just early stages trying to visualize it?

**Comment by kenzo44** [comment]
This is just a quick mockup in figma. 

It will behave similar to the preferences page - Users can see the headings once they open the config builder and choose which one they would like to expand.

Initially, I was thinking of doing it like the android settings page. Instead of dropdowns, having separate pages open for each category.

<img width="364" alt="Screenshot 2024-12-02 at 3 18 50 PM" src="https://github.com/user-attachments/assets/22e39bdd-f30b-42e0-833f-7cf0f06afa51">

We need to update the preferences page as well - We can expand headings but not collapse them.

**Comment by olorinmaia** [comment]
Great idea about improving preferences also, I was looking at how to remove the word "advanced" from every block but it seemed to origin from a read-only file so that kind of stopped me as of now ;)

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/37b5386875c95861da76288b19b5d0314fe1b8b9
