### ISSUE TITLE
[3.0-beta1] Automation issues with temporary/durational %profile change 

### ISSUE THREAD

**Issue by kristinsmotz** [nightscout/AndroidAPS#777]
I have noticed a couple of discrepancies when using automations to create % profile change with duration. 

1. precondition "Profile pct is equal to 100" is ignored.
Automation runs several times as long as the other conditions are met. In this case using the following conditions:
- Glucose is greater than 12.0 mmol
AND 
- Delta is equal or greater than 0.4
AND
- Last bolus time is equal or greater than 150 min ago
This automation is set to run a 130% profile change for 20 minutes

Automation ran a total of 4 times at 18.24, 18.29,18.34 and 18.39.

2. end time for profile duration doesn't update when automation is "renewed" due to error 1 described above
The timer next to the profile name in Overview tab counted down to the original end time from the first run of the automation, then started counting with negative numbers. On this occasion I manually ended the temporary profile change by setting a new permanent profile change at 18.59. 

Additional info: 
I did another observation the next time the automation kicked in. This time it ran only twice. I waited to see what would happen after the second round ran out of time, and it then cancelled the temporary profile change correctly. 

![247531597_2955325118070200_3978968117241261947_n (1)](https://user-images.githubusercontent.com/71758682/138592560-16e39957-ab49-4910-8f73-e91a2410431f.jpg)
![247858722_2070237293146886_1202914780265696841_n (1)](https://user-images.githubusercontent.com/71758682/138592561-8908f23d-1927-4f57-b5a6-9ad456168efc.jpg)
![247839525_6264456983596432_1272639861926333715_n (1)](https://user-images.githubusercontent.com/71758682/138592562-79eac413-1077-4d53-93ba-4cd1a49a13cb.jpg)

**Comment by tanja3981** [comment]
@MilosKozak I saw the same issue in beta6:
I have two automations that have the 100% profile precondition, which trigger at different BG values. 
If the higher BG is reached, it would set a higher profile.
If the lower of both BGs is reached, this shouldn't trigger as the first automation would have already did a temporary profile change. However, it does trigger, too.
Could this be a timing issue, because the profile switch takes some seconds to be applied and the second automation rule is evaluated before that?
(I'm using omnipod, so profile changes are slower than with dana pump...)

However, apart from this propably misusing the system and I could add additional conditions to the second automation rule, this does work differently than the current release and we should add a note to the release notes. indicating so.

**Comment by MilosKozak** [comment]
can be ....
is it possible to replicate it on fresh aaps?

**Comment by tanja3981** [comment]
@MilosKozak Yes, was able to reproduce on a spare phone with deleted database. Attached you can find the logfile.
You can see that both automations are evaluated. The profile switch done by the first automation is not taken into account during the evalutation of the second automation rule.
[AndroidAPS.log](https://github.com/nightscout/AndroidAPS/files/7577127/AndroidAPS.log)
